# Generated by Django 4.2.30 on 2026-08-20 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.localdate, help_text="The date this product was actually added to your inventory. Editable — doesn't have to be today (useful when entering older notebook records).", verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_label',
            field=models.CharField(help_text="Just a descriptive label, e.g. '90ml', '400ml', '500g', '1kg'. It does NOT affect how stock is counted below.", max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('box', 'Box'), ('pack', 'Pack')], default='pcs', help_text="How you count stock for THIS item — usually 'Pieces', even for a bottled/boxed item labelled '700ml' (you're tracking bottles, not raw millilitres). Only choose kg/g/l/ml if you sell loose/bulk quantities with no discrete units (e.g. rice sold by weight).", max_length=10, verbose_name='Stock counted in'),
        ),
    ]
