# Generated by Django 4.2.30 on 2026-08-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_date_added_alter_productvariant_size_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The parent company that owns this brand (optional, but recommended for accurate reporting).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='inventory.company'),
        ),
    ]
